name: 🚀 Update Space Shooter Game

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest

    steps:

      # 📥 Checkout your repository
      - name: 📥 Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      # 🐍 Setup Python
      - name: 🐍 Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      # 📦 Download Space Shooter source
      - name: 📦 Download Space Shooter
        run: |
          git clone --branch v2.0.0 --depth 1 \
            https://github.com/czl9707/gh-space-shooter.git \
            space-shooter

      # 🛠️ Add month labels to Space Shooter
      - name: 🗓️ Modify Space Shooter Calendar
        run: |
          python scripts/patch_space_shooter.py

      # 📦 Install modified Space Shooter
      - name: 📦 Install Space Shooter
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./space-shooter

      # 🚀 Generate modified Space Shooter
      - name: 🚀 Generate Space Shooter
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh-space-shooter \
            "${{ github.repository_owner }}" \
            --output game.gif \
            --strategy random \
            --fps 40

      # 💾 Commit game
      - name: 💾 Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add game.gif

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🚀 Update Space Shooter"
            git push
          fi
